apiVersion: v1
kind: Service
metadata:
  name: filemanager-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: filemanager
  ports:
  - port: 40000
    targetPort: 40000
    nodePort: 31002
  externalTrafficPolicy: Cluster
