apiVersion: apps/v1
kind: Deployment
metadata:
 name: kubernetes-multmatrix
 namespace: default
spec:
 replicas: 3
 selector:
  matchLabels:
   app: multmatrix
 template:
  metadata:
   labels:
    app: multmatrix
  spec:
   containers:
   - name: kubernetes-multmatrix
     image: docker.io/tianfsg/multmatrix:1.18
     volumeMounts:
      - mountPath: /prueba
        name: directorio-prueba
   volumes:
   - name: directorio-prueba
     hostPath:
      path: /home/ubuntu/compartido
      type: Directory
