apiVersion: v1
kind: Service
metadata:
 name: multmatrix-entrypoint
 namespace: default
spec:
 type: NodePort
 selector:
  app: multmatrix
 ports:
  - port: 40000
    targetPort: 40000
    nodePort: 31002
 externalTrafficPolicy: Cluster
